name: open-webui

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPEN_WEBUI_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WEBUI_AUTH_TRUSTED_PROXY=*
    volumes:
      - ${OPEN_WEBUI_CONFIG_PATH}:/app/backend/data
    restart: always
